safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"

title: "Commonjava :: Partyline"
tagline: "Joinable File I/O Streams"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org