safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"
      author: "John Casey"

siteTitle: "Commonjava"
projectTitle: "Partyline"
tagline: "Joinable File I/O Streams"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org

